### ISSUE TITLE
Сделайте функцию автовоспроизведения

### ISSUE THREAD

**Issue by pillaks** [N-point-N/ricktube#11]
Сделайте функцию автовоспроизведения. Например чтобы она включалась/выключалась в настройках. Или как на ютубе, в строке видео (там где качество, скорость воспроизведения и так далее).

**Comment by N-point-N** [comment]
Автовоспроизведение - это вы о том, чтобы после загрузки по ссылке сразу начинало воспроизводить или о том, чтобы следующий ролик открывался?
На ютубе как раз в строке видео насколько я понимаю регулируется как раз переключение на следующее видео

**Comment by pillaks** [comment]
Я имею в виду как раз чтобы после загрузки по ссылке сразу начинало воспроизводить видео.
Это намного удобнее чем потом нажимать чтобы видео запускалось. Ну и конечно надо сделать чтобы эту функцию можно было отключать.

**Comment by N-point-N** [comment]
Сделано, уже можно использовать :)
