### ISSUE TITLE
Проблема с видео

### ISSUE THREAD

**Issue by Pawl2020** [N-point-N/ricktube#13]
Почему-то на этом видео ваш сайт показывает качество 360p проверьте в чём проблема.
Ссылка с Ютуба:https://www.youtube.com/watch?v=Ana2CH1bBac
Ссылка с RickTube:https://ricktube.ru/watch/Ana2CH1bBac

**Comment by N-point-N** [comment]
Подскажите, на основании чего вы сделали вывод про 360р?
Насколько вижу, сайт не отображает разрешение

**Comment by N-point-N** [comment]
А, нашел, да, почему-то вы качал 360р, странно, проверю почему захватил именно его, устраню

**Comment by N-point-N** [comment]
Дубликат https://github.com/N-point-N/ricktube/issues/25
