### ISSUE TITLE
Видео, требует подтверждение возраста

### ISSUE THREAD

**Issue by MedZveD** [N-point-N/ricktube#21]
Добрый день!
Есть такие видео...даже без прона и расчлененки.
Например, https://www.youtube.com/watch?v=06yR8WbIaPY 
Попытка просмотреть выдает:
![image](https://github.com/user-attachments/assets/39b10cc5-6124-417d-9e0d-d220c87c76ab)

Предлагаю, по умолчанию проставить "совершеннолетняя, Жень".

**Comment by MedZveD** [comment]
"И тут мне как поперло..."
https://www.youtube.com/watch?v=L0LWe-ObYGs
![image](https://github.com/user-attachments/assets/40a73945-ecbc-48c9-acc7-c9cac07bc491)

**Comment by imbalon** [comment]
+1
![image](https://github.com/user-attachments/assets/2b5daf1b-4aef-4aa7-ad5b-c452c364c088)

**Comment by MedZveD** [comment]
https://ricktube.ru/watch/m9XayJB5BqE

**Comment by N-point-N** [comment]
Добрый!
Прошу прощения за долгий ответ, да, серьезный баг, сделано временное решение, но возможно повторение
Задача остается открытой до окончательной починки

**Comment by N-point-N** [comment]
Импорт метаданных переведен на револьверный прокси балансир, проблема должна быть исправлена навсегда, закрываю до воспроизведения
