### ISSUE TITLE
Некоторые видео зависают при старте

### ISSUE THREAD

**Issue by MedZveD** [N-point-N/ricktube#22]
https://ricktube.ru/watch/ZsGOJiLCvrc
Данное видео не первый день отказывается стартовать
![image](https://github.com/user-attachments/assets/5f8d05ee-fe65-4173-9625-32e398266cf8)

**Comment by N-point-N** [comment]
Хм, похоже таска зависла, перекачал данное видео - пока единичный случай, если будет повторяться - сделаю более детальный разбор
