### ISSUE TITLE
Выбор качества видео

### ISSUE THREAD

**Issue by yaposhe** [N-point-N/ricktube#23]
Невозможно выбрать качество видео. По ощущениям на все видео ставится 720p

**Comment by N-point-N** [comment]
В данный момент, верно, качество заранее зашито для бесплатного тарифа одно, с подпиской - другое
Возможно появится возможность доступа к разным разрешениям, когда доделаю задачу с мгновенным воспроизведением, без ожидания полной загрузки :)
