### ISSUE TITLE
Кэширование видео

### ISSUE THREAD

**Issue by yaposhe** [N-point-N/ricktube#24]
Почему-то в последнее время даже 720p видео стало тормозить, что на домашнем, что на мобильном интернете. Секунду покажет - две грузит, секунду покажет - 2 грузит и тд. В ютубе же есть возможность кэширования, когда ставишь видео на паузу, а оно прогружается дальше.

**Comment by N-point-N** [comment]
Вообще кеширование работает из коробки, сейчас проверяю - все в порядке с проводного подключения
Можете пожалуйста подсказать браузер ,версию, и какой интернет?

**Comment by yaposhe** [comment]
МТС мобильный, браузер chrome android. Вот сегодня по дефолту было 480p разрешение, и все ок было. На 720p ни разу не повысилось

**Comment by N-point-N** [comment]
Принято, 720р пока на паузе - яндекс трафик накидал, чтоб не зависли все видео вообще до разрешения проблемы с ресурсами - ограничил до 480р на бесплатном тарифе
Закрою задачу, создайте пожалуйста, если будут снова проблемы
