### ISSUE TITLE
RickTube улучшения

### ISSUE THREAD

**Issue by Pawl2020** [N-point-N/ricktube#4]
Хочется добаввить поддержку плейлистов с Ютуб
Хочется чтобы вы на ricktube скопировали функцию воспроизведения с постоянным уровнем громкости, как на Ютубе.
![Снимок экрана (334)](https://github.com/user-attachments/assets/469dbda2-300d-4b99-b01a-80dab65fd32c)

**Comment by N-point-N** [comment]
Пожалуйста оформите каждое пожелание в виде отдельной задачи с ее названием в заголовке и комментарием в описании (если нужен)
