### ISSUE TITLE
Добавьте функцию "Картинка в картинке"

### ISSUE THREAD

**Issue by pillaks** [N-point-N/ricktube#8]
Добавьте функцию "Картинка в картинке"
Например, выходишь с сайта, а в 1 из углов у тебя маленькое окошко c этим видео (так было сделано в youtube shorts) 
А также было бы круто если бы ты пролистывал видео вниз (например чтобы посмотреть описание) и у тебя тоже появлялась маленькое окошко с видео (так было сделано в одном браузерном расширении для youtube)

**Comment by N-point-N** [comment]
Будет реализовано примерно к 12 октября, отпишу в это обращение

**Comment by Stardisk** [comment]
Касаемо "картинки в картинки", на ютубе, если два раза щелкнуть правой кнопкой мыши, то вываливается стандартное меню для тега `<video>`, где как раз есть пунктик "картинка в картинке", которую можно таскать за пределы браузера на любое место рабочего стола и любого монитора. Хотелось бы подобное и у вас)

**Comment by N-point-N** [comment]
Сделано, можете пользоваться :)

**Comment by N-point-N** [comment]
Сделано, можете пользоваться :)
